
version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "kirill"
      POSTGRES_PASSWORD: "postgres"
 
    ports:
      - "5433:5432"

  nats-streaming:
    # command:
    # - nats-streaming
    image: nats-streaming
    container_name: nats-streaming
    ports:
    - 4222:4222
 